### PR TITLE
add enable_hw_sync to deploy params

### PR DESCRIPTION
**Pull request by mastier**
Let's add new MAAS deployment parameter, introduced in the version 3.2
https://maas.io/docs/how-to-customise-machines#heading--how-to-enable-hardware-sync-on-a-machine

### CODE REVIEW

**Comment by sparkiegeek** [comment]
Related to #57

**Review by cpg1111 — APPROVED** [review]
+1

**Comment by pescobar** [comment]
Thanks for looking into this issue.

JFYI I built the provider from this PR but it's still not working for me. 

If you need anyone for testing let me know, I can help if needed.

**Comment by troyanov** [comment]
> JFYI I built the provider from this PR but it's still not working for me.
> 
> If you need anyone for testing let me know, I can help if needed.

Hi @pescobar 
Thank you for your help with testing this. 
It seems that this PR was missing mapping from terraform resource schema to gomaasclient structs, which was fixed in 105382b9094ad4bd455298ce52aff4960395ec6c. 

Can you please give one more try and build provider from this PR?

**Comment by pescobar** [comment]
@troyanov thanks for the quick fix!

I tested https://github.com/mastier/terraform-provider-maas/commit/95829c742958dc1a65148e5b710518c18fe7689e and it's working :)

**Comment by sparkiegeek** [comment]
@troyanov think this also needs a doc update?

**Comment by pescobar** [comment]
Thanks for the quick release @troyanov 

In case it helps this is how I deployed a `maas_instance` with hardware sync enabled

```
resource "maas_instance" "node04" {
    depends_on = [maas_machine.node04]
    allocate_params {
        hostname = maas_machine.node04.hostname
        pool     = "default"
        zone     = "default"
    }
    deploy_params {
        distro_series = "jammy"
        enable_hw_sync = true
    }
}
```

**Pull request merged**
